# .readthedocs.yaml
version: 2

sphinx:
  configuration: docs/conf.py  # Path to your Sphinx conf.py

build:
  image: latest  # Valid: specifies the RTD build image

python:
  version: 3.11
  install:
    - requirements: docs/requirements.txt
