variable "name" {}
variable "aws_region" {}
variable "aws_azs" {}
variable "enable_dns_hostnames" {}
variable "vpc_cidr_block" {}
variable "public_subnets_cidrs" {}
variable "private_subnets_cidrs" {}
variable "common_tags" {}
variable "naming_prefix" {}